
eureka:
  client:
    eureka-server-connect-timeout-seconds: 5
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/

server:
  port: 8761