feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

spring:
  application:
    name: library-web

server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8777/eureka